### ISSUE TITLE
Reducing time it takes for emails to be sent

### ISSUE THREAD

**Issue by aearleycaw** [moodleou/moodle-mod_forumng#53]
Hello, I am trying to use ForumNG as a means of technical support, this means resonses will be required to be fast however the notification emails are sent out an hour after the post. 
I thought at first it shared the same time as the regular forum activity but the time period on that is 5 minutes.

**Comment by jason-platts** [comment]
You can configure the emailing schedule time (If on Moodle 2.8+).

You need to change the 'email_normal' scheduled task to run more often than every hour.

You can then also change the core setting 'maxeditingtime' to a lower value if the posts need to be sent without delay after creation. (There is also a 'mail now' option when creating a post which does the same thing, this is controlled by mod/forumng:mailnow capability)

**Comment by aearleycaw** [comment]
Sadly I am only running on Moodle 2.7, is there a way I can do with with 2.7?

**Comment by jason-platts** [comment]
I think it will also work in 2.7 if you change the forumng cron frequency in the modules table.

**Comment by aearleycaw** [comment]
Currently the cron value is 0. If I wished for an instant email to be sent out, what would the value need to be changed to?
