### ISSUE TITLE
Attachment size limit when addiing file via WYSIWYG

### ISSUE THREAD

**Issue by mfindlayated** [moodleou/moodle-mod_forumng#55]
Hi folks,

We are seeing an issue when adding files/images to a forum post (rathert than uploading as an attachment), that if the filesize is bigger than that set by the attachment file limit, then the file seems to upload, but them doesn't appear in the post.

Is this a bug or intended behavior? If it is intended then it would be better if you get a pop up error message which didn't allow you to upload. This behaviour does't appaer to ahppen in the Moodle 'standard' forum.

We are using Moodle 2.8.6+ and ForumNG 2015060500

Thanks in advance,
Mark.

**Comment by jason-platts** [comment]
Thanks. I see this as well.

We hadn't spotted this as it actually works as expected in our theme (so maybe it works ok on other older themes?).

As we're switching to a new bootstrap theme soon we'll need to fix this!

**Comment by sleperf** [comment]
In the file editpost_form.php you should add the maxbytes in the editor options for the field message

**Comment by jason-platts** [comment]
Fixed in master + 3.0+ versions

3ef013edf257d8aa4f268de501f035645fc86653
