### ISSUE TITLE
Plugin forumngfeature_copy does not declare valid $plugin->component in its version.php.

### ISSUE THREAD

**Issue by nitro2010** [moodleou/moodle-mod_forumng#57]
Hello,

Please update your plugin for Moodle v3.0

While installating I get errors [all text with debugging option on]:

Plugin forumngfeature_copy does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin forumngfeature_delete does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin forumngfeature_deletedposts does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin forumngfeature_edittags does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin forumngfeature_export does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin forumngfeature_flagdiscussion does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin forumngfeature_forward does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin forumngfeature_lock does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin forumngfeature_manualmark does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin forumngfeature_markallread does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin forumngfeature_markdiscussionread does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin forumngfeature_merge does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin forumngfeature_move does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin forumngfeature_options does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin forumngfeature_print does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin forumngfeature_sticky does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin forumngfeature_usage does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin forumngfeature_userposts does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin forumngtype_clone does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin forumngtype_general does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin forumngtype_studyadvice does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()

**Comment by jason-platts** [comment]
Fixed by #56 : Will be upstream in the future, till then you can use the patch.
