### ISSUE TITLE
ForumNG won't install on Moodle v3

### ISSUE THREAD

**Issue by mfindlayated** [moodleou/moodle-mod_forumng#63]
Hi,

I am trying to instal ForumNG on our v3 Sandpit, and it is failing with the following error:

"Plugin "forumngfeature_copy" is defective or outdated, can not continue, sorry."

Debug info: Missing $plugin->component declaration in version.php.
Error code: detectedbrokenplugin
Stack trace:

    line 459 of /lib/upgradelib.php: plugin_defective_exception thrown
    line 1647 of /lib/upgradelib.php: call to upgrade_plugins()
    line 677 of /admin/index.php: call to upgrade_noncore()

We've seen this error a lot with older plugins and the fix is quite easy, add '$plugin->component = 'mod_formmg' to version.php';

However as these are 'sub' plugins of ForumNG, I'm not ure what the plugintype should be, would 
$plugin->component = 'mod_forumngfeature_copy'

suffice in this instance?
Cheers,
Mark.

**Comment by jason-platts** [comment]
This is fixed in Master branch already, see:
https://github.com/moodleou/moodle-mod_forumng/commit/af6eb1e893ced96985b688fb4afd469c464cf805
