### ISSUE TITLE
3.1 Tag API - unit test failures

### ISSUE THREAD

**Issue by aspark21** [moodleou/moodle-mod_forumng#64]
Moodle 3.1 latest stable / ForumnNG master branch
DB - pgsql & mysqli
Aware of the [release schedule](http://learn1.open.ac.uk/mod/oublog/viewpost.php?post=0&u=sm449&time=1369232093), logging for reference.

Debugging: Method tag_delete() is deprecated, use core_tag_tag::delete_instances()
- line 3619 of /lib/deprecatedlib.php: call to debugging()
- line 1219 of /mod/forumng/mod_forumng.php: call to tag_delete_instances()
- line 95 of /mod/forumng/lib.php: call to mod_forumng->delete_all_data()
- line 1745 of /course/lib.php: call to forumng_delete_instance()
- line 251 of /mod/forumng/tests/rating_test.php: call to course_delete_module()
- line ? of unknownfile: call to mod_forumng_rating_testcase->test_rating()
- line 908 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to ReflectionMethod->invokeArgs()
- line 768 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit_Framework_TestCase->runTest()
- line 80 of /lib/phpunit/classes/advanced_testcase.php: call to PHPUnit_Framework_TestCase->runBare()
- line 612 of /vendor/phpunit/phpunit/src/Framework/TestResult.php: call to advanced_testcase->runBare()
- line 724 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit_Framework_TestResult->run()
- line 747 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit_Framework_TestCase->run()
- line 747 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
- line 747 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
- line 440 of /vendor/phpunit/phpunit/src/TextUI/TestRunner.php: call to PHPUnit_Framework_TestSuite->run()
- line 149 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit_TextUI_TestRunner->doRun()
- line 100 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit_TextUI_Command->run()
- line 47 of /vendor/phpunit/phpunit/phpunit: call to PHPUnit_TextUI_Command::main()

Related Unit Test Failures
1) mod_forumng_discussion_testcase::test_tag_discussion
dml_write_exception: Error writing to database (ERROR:  invalid input syntax for integer: "Array"
INSERT INTO p_forumng (course,tags,name,intro,introformat,magicnumber) VALUES($1,$2,$3,$4,$5,$6) RETURNING id
[array (
  'course' => '140000',
  'tags' => 
  array (
    0 => '1',
  ),
  'name' => 'ForumNG 1',
  'intro' => 'Test forum 1',
  'introformat' => '0',
  'magicnumber' => '2448412256245348',
)])
/home/travis/build/aspark21/moodle/lib/dml/moodle_database.php:477
/home/travis/build/aspark21/moodle/lib/dml/pgsql_native_moodle_database.php:244
/home/travis/build/aspark21/moodle/lib/dml/pgsql_native_moodle_database.php:898
/home/travis/build/aspark21/moodle/lib/dml/pgsql_native_moodle_database.php:954
/home/travis/build/aspark21/moodle/mod/forumng/lib.php:57
/home/travis/build/aspark21/moodle/course/modlib.php:121
/home/travis/build/aspark21/moodle/lib/testing/generator/module_generator.php:266
/home/travis/build/aspark21/moodle/mod/forumng/tests/generator/lib.php:84
/home/travis/build/aspark21/moodle/mod/forumng/tests/forumng_discussion_test.php:215
/home/travis/build/aspark21/moodle/lib/phpunit/classes/advanced_testcase.php:80
To re-run:
 vendor/bin/phpunit mod_forumng_discussion_testcase mod/forumng/tests/forumng_discussion_test.php
2) mod_forumng_rating_testcase::test_rating
Unexpected debugging() call detected.
/home/travis/build/aspark21/moodle/lib/phpunit/classes/advanced_testcase.php:88
To re-run:
 vendor/bin/phpunit mod_forumng_rating_testcase mod/forumng/tests/rating_test.php

**Comment by aspark21** [comment]
Hey chaps, 

Just wondering when you might be doing the next round of public release for the OU plugins. Most of them are affected by this & we are looking at 3.1 upgrades with these being the only outstanding blocker so it would help if we knew when we might be able to schedule things based on that info.

Thanks!

**Comment by jason-platts** [comment]
Fixed in master - sorry about the delay in pushing the fixes...
