### ISSUE TITLE
Issue with 3.1 when 

### ISSUE THREAD

**Issue by aearleycaw** [moodleou/moodle-mod_forumng#69]
When trying to edit the settings for ForumNG in 3.1 the below error message is displayed.
This is followed by a number of Arrays hat contain information such as the description.

![image](https://cloud.githubusercontent.com/assets/15140497/20921550/987d3bf0-bb9c-11e6-894b-cfc0cebb437c.png)

This is shown in the header and the edit settings page is located below.

**Comment by jason-platts** [comment]
You need to use the latest master or 3.1 branches if you are running on 3.1... a Moodle plugins release is coming...
