### ISSUE TITLE
Gradebook not updating

### ISSUE THREAD

**Issue by davidlanier** [moodleou/moodle-mod_forumng#70]
When changing only the title of an instance of ForumNG the gradebook items are not updated. We found that it is necessary to change the grade type, scale, or rating in order to call update_grades(). This can become quite a tedious task in Moodle when you have several forums in a course.

Recommend removing the if conditional in mod_forumng.php beginning at line 1130 and just simply calling `$this->update_grades();` without any condition.

`
if ($previousfields->grading != $this->forumfields->grading ||
            $previousfields->ratingscale != $this->forumfields->ratingscale ||
            $previousfields->gradingscale != $this->forumfields->gradingscale) {
                  $this->update_grades();
 }
`

**Comment by jason-platts** [comment]
This is fixed in the latest code version, thanks for raising the issue...
