### ISSUE TITLE
Error detected in a function (feature userposts)

### ISSUE THREAD

**Issue by echiffre** [moodleou/moodle-mod_forumng#71]
Hi,

I think I found an error in a file mod/forumng/feature/userposts/forumngfeature_userposts.php 
Function display(), Line 64-65
_return parent::get_button($forum, $name, $script, false, array('user' => mod_forumng_utils::get_real_userid(), 'fng-mobile-on'));_
The parameters of the function are not correct : I think it should be
_return parent::get_button($forum, $name, $script, false, array('user' => mod_forumng_utils::get_real_userid()), '', 'fng-mobile-on');_

The class 'fng-mobile-on' should not be in a array. No ?

Eliane

**Comment by jason-platts** [comment]
Fixed in next release, thanks for spotting.
